###consul服务端口号
server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
####consul注册中心地址
  cloud:
    consul:
      host: 39.96.82.151
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}